### ISSUE TITLE
Reports UI todo list

### ISSUE THREAD

**Issue by jcii** [SavageLearning/Machete#239]
- [ ] adjustable width
- [ ] search table text
- [ ] race condition on startup 
- [ ] adjust column names in SQL queries
- [ ] show SQL button, format code in display
